export const CRIMES = [
	'Tried to wrestle an alligator out of a public swimming pool',
	'Drove a lawnmower through a fast food drive-thru',
	'Stole a truck full of oranges and led police on a slow-speed chase',
	'Dressed up as a clown and robbed a convenience store',
	'Used a sword to fight off imaginary ninjas in a public park',
	'Tried to steal a boat while wearing a bikini',
	'Smuggled a python onto a plane by hiding it in a suitcase',
	'Tried to rob a bank using a toy gun',
	'Used a blowtorch to break into a vending machine',
	'Dressed up as a superhero and tried to stop a tornado',
	'Tried to start a forest fire by setting off fireworks during a drought',
	'Smashed a car window to rescue a mannequin from a hot car',
	'Tried to rob a gas station using a potato peeler',
	'Used a chainsaw to cut down a "no trespassing" sign on a private property',
	'Tried to pay for a meal with a live crab',
	'Dressed up as a mermaid and tried to swim in a public fountain',
	'Used a metal detector to dig up a beach volleyball court during a game',
	'Tried to rob a convenience store while wearing a cowboy hat and boots',
	'Used a baseball bat to smash a car window to retrieve a forgotten cellphone',
	'Tried to start a car with a screwdriver and a piece of bubble gum',
	'Dressed up as a dinosaur and tried to rob a museum',
	'Tried to pay bail with a bag of loose change and bottle caps',
	'Used a flamethrower to clear a patch of weeds in a public park',
	'Tried to rob a gas station using a water gun',
	'Used a hammer to break into a zoo to pet a sleeping panda',
	'Tried to steal a kayak by floating away in it while wearing a wedding dress',
	'Dressed up as a pirate and tried to hijack a tour boat',
	'Used a chainsaw to carve a statue in a public park',
	'Tried to rob a convenience store while wearing a wedding veil',
	'Used a vacuum cleaner to suck up seashells from a public beach',
	'Used a flamethrower to dry a wet car after washing it',
	'Tried to rob a bank while wearing a shark costume',
	'Used a machete to chop down a tree in a public park to make a swing',
	'Tried to break into a house by climbing up the chimney and getting stuck',
	'Used a baseball bat to smash a store window to steal a lottery ticket',
	'Dressed up as a cow and tried to steal a milk truck',
	'Used a chainsaw to create a Christmas tree sculpture in a public park in July',
	'Tried to rob a gas station with a banana',
	'Used a flamethrower to melt snow on a public sidewalk',
	'Tried to steal a car by breaking into it and falling asleep inside',
	'Dressed up as a leprechaun and tried to rob a bank on St. Patrick\'s Day',
	'Used a machete to cut a trail through a city park to make a shortcut',
	'Used a baseball bat to smash a mailbox in a fit of passion',
	'Drove a bumper car on a busy highway',
	'Smuggled a penguin into a hotel room',
	'Tried to steal a statue using a remote-controlled car',
	'Dressed up as a clown and performed magic tricks during a funeral service',
	'Put a fake parking ticket on a police car',
	'Threw a surprise party in a movie theater during a screening',
	'Tried to sell fake diplomas to unsuspecting students',
	'Used a drone to fly a love letter over a prison wall',
	'Tried to rob a bank while wearing roller skates',
	'Used a megaphone to sing karaoke on a crowded bus',
	'Tried to sneak a lizard into a concert in their shirt pocket',
	'Dressed up as a pirate and tried to board a cruise ship',
	'Tried to sell a "chocolate fountain" made of mud to unsuspecting buyers',
	'Used a slingshot to launch water balloons at a parade',
	'Tried to bribe a police officer with a bag of candy canes',
	'Used a leaf blower to scatter a stack of money on a busy street',
	'Tried to pay for a cab ride with a handful of paperclips, ran away when the driver refused',
	'Dressed up as a giant squirrel and chased people in a park',
	'Used a catapult to launch a watermelon at a car',
	'Tried to sell "miracle water" to unsuspecting victims',
	'Used a remote-controlled car to create a traffic jam',
	'Dressed up as a superhero and tried to stop a train',
	'Used a pogo stick to jump over a crowd of people',
	'Tried to steal a police car while wearing a chicken suit',
	'Used a megaphone to give unsolicited life advice on a street corner',
	'Dressed up as a giant pineapple and tried to enter a nightclub',
	'Used a slingshot to launch pies at a food festival',
	'Tried to bribe a customs agent with a bag of lollipops',
	'Used a remote-controlled helicopter to fly a banner over a wedding ceremony',
	'Tried to sell a "healing crystal" to unsuspecting buyers',
	'Used a pogo stick to jump over a row of parked cars',
	'Dressed up as a unicorn and tried to start a parade',
	'Used a megaphone to lead a sing-along in a library',
	'Tried to steal a police horse while wearing a tutu',
	'Used a slingshot to launch candy at a parade float',
	'Dressed up as a giant banana and tried to join a marching band',
	'Used a remote-controlled boat to create a traffic jam in a canal',
	'Tried to bribe a security guard with a bag of gummy worms',
	'Used a pogo stick to jump over a pool of Jello',
	'Tried to sell "rainbow-colored sand" to unsuspecting buyers',
	'Used a megaphone to give a motivational speech to people waiting in line at the DMV',
	'Tried to sneak a live lobster onto a plane in their luggage',
	'Used a slingshot to launch tomatoes at a cooking competition',
	'Used a bubble gun to rob a bank',
	'Tried to smuggle a live goat into a movie theater',
	'Wore a horse mask and tried to rob a convenience store',
	'Made a fake speed limit sign and posted it on a busy street',
	'Repeatedly tried to pass off Monopoly money as real currency',
	'Used a water balloon launcher to throw pies at a politician\'s rally',
	'Put a "Wet Paint" sign on a police car',
	'Tried to sell a "haunted" house to unsuspecting buyers',
	'Used a megaphone to shout their own name during a silent meditation retreat',
	'Tried to rob a jewelry store using a banana',
	'Dressed up as a dinosaur and tried to block traffic',
	'Stole a giant inflatable duck and set it adrift in a river',
	'Tried to sneak a pet alligator onto a train',
	'Wore a giant turkey costume and tried to board a plane without a ticket',
	'Used a frisbee to knock over a mailbox',
	'Tried to bribe a security guard with a bag of chips',
	'Used a fake hand to hitchhike on a busy road',
	'Put a "No Parking" sign on a police car',
	'Tried to sell a "time machine" to unsuspecting buyers',
	'Used a catapult to launch water balloons at a police station',
	'Wore a giant traffic cone on their head and tried to enter a museum',
	'Used a pogo stick to jump over a mall fountain',
	'Tried to sell a "miracle cure" to unsuspecting victims',
	'Used a kazoo to interrupt a church service',
	'Dressed up as a ghost and tried to scare people at a car wash',
	'Tried to steal a police car to impress their friends',
	'Used a potato gun to create crop circles in a farmer\'s field',
	'Used a grappling hook to break into a toy store',
	'Wore a giant top hat and tried to enter a courthouse',
	'Tried to sell a "magic rock" to unsuspecting buyers',
	'Used a remote-controlled car to steal candy from a vending machine',
	'Used a squirt gun to spray mustard all over a hot dog stand',
	'Tried to bribe a customs agent with a bag of candy',
	'Dressed up as a superhero and tried to stop a marathon',
	'Used a unicycle to ride on the ceiling of a shopping mall',
	'Tried to steal a police officer\'s badge',
	'Used a megaphone to give an impromptu speech in a crowded movie theater',
	'Used a remote-controlled drone to deliver love letters to unsuspecting people',
	'Tried to sell a "lucky charm" to unsuspecting buyers',
	'Used a pogo stick to jump over a line of cars waiting at a red light',
	'Used a whoopee cushion to disrupt a job interview',
	'Tried to sneak a live flamingo onto a plane in their backpack',
	'Used a water gun to steal a bank teller\'s pen',
	'Tried to smuggle a live lobster out of a restaurant in their pants',
	'Wore a giant chicken suit and jaywalked across a busy street',
	'Made a ransom note using cut-out letters from a crossword puzzle',
	'Used a slingshot to launch paintballs at a police car',
	'Put a "Kick Me" sign on a police officer\'s back',
	'Tried to sell a counterfeit painting to an art museum',
	'Used a megaphone to shout their own name in a quiet library',
	'Tried to rob a convenience store using a toy lightsaber',
	'Dressed up as a superhero and tried to stop traffic',
	'Stole a fire extinguisher and sprayed it all over a crowded mall',
	'Tried to sneak a pet snake onto an airplane',
	'Wore a giant sombrero and tried to board a train without a ticket',
	'Used a frisbee to break into a vending machine',
	'Tried to bribe a police officer with a box of donuts',
	'Used a fake hand to shoplift from a store',
	'Put a "Free Hugs" sign on a police barricade during a protest',
	'Tried to sell a bag of air to a tourist',
	'Used a catapult to launch eggs at a building',
	'Wore a full suit of armor and tried to get into a nightclub',
	'Used a pogo stick to jump over a police car',
	'Tried to sell a piece of the Berlin Wall on eBay',
	'Used a kazoo to disrupt a city council meeting',
	'Dressed up as a ghost and scared people in a cemetery after hours',
	'Tried to steal a fire truck to impress their date',
	'Used a potato gun to vandalize a billboard',
	'Used a grappling hook to break into a donut shop',
	'Wore a giant top hat and tried to sneak into a museum after hours',
	'Tried to sell a jar of air from a famous musician\'s concert',
	'Used a remote-controlled car to transport stolen goods',
	'Used a squirt gun to spray ketchup all over a fast food restaurant',
	'Tried to bribe a judge with a box of chocolates',
	'Dressed up as a superhero and tried to stop a parade',
	'Used a unicycle to ride on the sidewalk in a no-biking zone',
	'Tried to steal a police officer\'s handcuffs',
	'Used a megaphone to sing karaoke in a public park after hours',
	'Used a remote-controlled drone to take selfies on top of a skyscraper',
	'Tried to sell a "miracle" weight loss supplement to unsuspecting victims',
	'Used a pogo stick to jump over a swimming pool',
	'Used a whoopee cushion to disrupt a wedding ceremony',
	'Tried to sneak a live parrot onto a plane in their backpack',
];