version: '3.8'
services:
    website:
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - ORIGIN=http://localhost
        build: .
        ports:
            - 9098:3000
        depends_on:
            - pocketbase
        restart: always
        networks:
            - faces-network
    pocketbase:
        build: ./src/pocketbase/
        restart: always
        env_file:
            - .env
        ports:
            - '9097:8080'
        networks:
            - faces-network
        volumes:
            - pocketbase-data:/pb
            - ./src/pocketbase/pb_migrations:/pb/pb_migrations

networks:
    faces-network:
        driver: bridge

volumes:
    pocketbase-data: {}
